// Canonical URL mappings: every folder a page has ever lived under, pointing at
// the one folder it lives under now.
//
// A book or author entry in `autore/index.json` may carry a `redirectPaths`
// array listing retired folders:
//
//   {
//     "name": "Kryengritja shqiptare",
//     "folder": "grameno/kryengritja-shqiptare",
//     "redirectPaths": ["grameno/kryengritja-e-shqiptareve"]
//   }
//
// The site is fully prerendered, so there is no server left to answer the old
// URL. Instead the build turns these into Cloudflare Pages `_redirects` rules
// (see the `canonical-redirects` plugin in vite.config.ts), which serve a real
// 301 — the only kind of redirect search engines transfer ranking through.
//
// This module reads the filesystem, so it is Node-only: import it from build
// tooling and server code, never from a component.

import * as fs from 'fs';
import type { Author } from './types';

const AUTHORS_INDEX = 'autore/index.json';

export type Redirect = {
  /** Retired path, with leading and trailing slash: `/grameno/old-book/` */
  from: string;
  /** Canonical path, with leading and trailing slash: `/grameno/new-book/` */
  to: string;
};

/** `grameno/x` | `/grameno/x/` -> `/grameno/x/` */
function toPath(folder: string): string {
  return `/${folder.trim().replace(/^\/+|\/+$/g, '')}/`;
}

/**
 * Every `redirectPaths` entry in the authors index, resolved to a single
 * `from -> to` pair per retired path.
 *
 * Throws rather than emitting a rule that would be wrong in production: a
 * self-redirect, a retired path that is also somebody's live folder (which
 * would make a reachable page unreachable), or two entries claiming the same
 * old path. All three are silent SEO damage if they ship.
 */
export function getRedirects(indexPath = AUTHORS_INDEX): Redirect[] {
  const index: Record<string, Author> = JSON.parse(
    fs.readFileSync(indexPath, 'utf-8'),
  );

  const canonical = new Set<string>();
  const claimed: Array<{ from: string; to: string; label: string }> = [];

  for (const author of Object.values(index)) {
    for (const entry of [author, ...(author.books ?? [])]) {
      if (!entry.folder) continue;

      const to = toPath(entry.folder);
      canonical.add(to);

      for (const retired of entry.redirectPaths ?? []) {
        claimed.push({
          from: toPath(retired),
          to,
          label: entry.name ? String(entry.name) : entry.folder,
        });
      }
    }
  }

  const resolved = new Map<string, string>();

  for (const { from, to, label } of claimed) {
    if (from === to) {
      throw new Error(
        `redirects: "${label}" lists its own folder ${from} in redirectPaths`,
      );
    }
    if (canonical.has(from)) {
      throw new Error(
        `redirects: ${from} is the live folder of another entry, so it cannot ` +
          `also redirect to ${to} (from "${label}")`,
      );
    }
    const other = resolved.get(from);
    if (other && other !== to) {
      throw new Error(
        `redirects: ${from} is claimed by both ${other} and ${to} — a retired ` +
          'path can only have one canonical target',
      );
    }
    resolved.set(from, to);
  }

  return [...resolved]
    .map(([from, to]) => ({ from, to }))
    .sort((a, b) => a.from.localeCompare(b.from));
}

/**
 * Render the rules as a Cloudflare Pages `_redirects` file.
 *
 * Two rules per mapping, because a splat only matches what follows the prefix:
 * `/old/*` covers `/old/` and everything beneath it, but not a bare `/old`.
 */
export function renderRedirects(redirects: Redirect[]): string {
  const lines = [
    '# Generated by the canonical-redirects plugin (vite.config.ts) from the',
    '# `redirectPaths` fields in autore/index.json. Do not edit by hand — this',
    '# file is rewritten on every build.',
  ];

  for (const { from, to } of redirects) {
    lines.push(
      '',
      `${from.replace(/\/$/, '')} ${to} 301`,
      `${from}* ${to}:splat 301`,
    );
  }

  return lines.join('\n') + '\n';
}

/**
 * Resolve `pathname` against `redirects`, or `null` if it is not a retired
 * path. Mirrors what the `_redirects` rules do in production.
 */
export function matchRedirect(
  redirects: Redirect[],
  pathname: string,
): string | null {
  const path = pathname.endsWith('/') ? pathname : `${pathname}/`;

  for (const { from, to } of redirects) {
    if (path === from) return to;
    if (path.startsWith(from)) return to + path.slice(from.length);
  }

  return null;
}
